### ISSUE TITLE
Large Text

### ISSUE THREAD

**Issue by luketlancaster** [nss-evening-cohort-12/chatty-zeta-star-wars#16]
## User Story
As a user, with tired eyes, I should be able to chat with large text.

## AC
**Given** A user navigates to your page
**Then** they should see a checkbox below the input field called "Large Text"
**And** they should be able to click this checkbox
**And** when the checkbox is selected all the message text should be larger

## Dev Notes
**To-Do**

- [x] create a checkbox that is located toward the top of the page

- [x] create a function that adjusts the size of the font on the page. This is callback function handles the logic. It adds a new CSS className to the all the paragraphs which has a class Name as a "font-class".

  #document.querySelector("p") 
  #element.classList.add("font-class");

- [x] create an event listener that runs the function that changes font size
- [x] remove the css class when the user unchecks the checkbox.
by removing the "font-class" as below.

  #document.querySelector("p") 
  #element.classList.remove("font-class");

**Moq-Up**
![large text](https://user-images.githubusercontent.com/62913995/84099017-47222a80-a9ce-11ea-98a1-3034ada111dc.png)
