### ISSUE TITLE
Delete Message

### ISSUE THREAD

**Issue by luketlancaster** [nss-evening-cohort-12/chatty-zeta-star-wars#17]
## User Story
As a user I should be able to delete messages my messages.

## AC
**Given** A message on your page
**Then** there should be a delete button for each message (that belongs to your user)
**And** when the button is pushed the message should no longer exist

## Dev Notes
# To-do
- [x] Place button on each message as seen in #2 
- [x] Set javascript functionality on click to splice the relevant message from the messages array created in #4 
- [x] Refresh the display show the updated array minus the deleted message

# Notes
- Will need to figure out how this will play with #19 -- if we're iterating a unique ID for each message, those IDs will need to adjust when a message object is removed from the array
- Directions in the AC specify deleting only messages belonging to your user, so we will need to make sure the buttons only appear on messages sent by the selected user
