### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by luketlancaster** [nss-evening-cohort-12/chatty-zeta-star-wars#20]
## User Story
As a developer I need a really nice readme.

## AC
**WHEN** looking at this repo
**THEN** I should see a really nice repo

## Dev notes
**To-Do**

- [x] Create a short description about the design and purpose of the app

- [x] create a portion detailing the features of the site

- [x] create a section on how to run the app

- [x] create a section that entails all devs that contributed to the app

- [x] create a section that showcases spinets of code for others to see
