### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by luketlancaster** [nss-evening-cohort-12/chatty-zeta-star-wars#3]
## User Story
As a user, with sensitive eyes, I should be able to chat using a dark theme.

## AC
**Given** A user navigates to your page
**Then** they should see a checkbox below the input field called "Dark Theme"
**And** they should be able to click this checkbox
**And** when the checkbox is selected the page should show a dark theme with lightly colored text

## Dev Notes
**To-Do**

- [x] create a checkbox at the top of the page and label it Dark Mode

- [x] Create a separate styling that uses dark colors

- [x] create an event listener that will be tied to the checkbox that will swap between the styling of the light and dark mode

- [x] attach the event listener to the checkbox and attach the separate styling to the event listener

**Moq-Up**
![dark theme](https://user-images.githubusercontent.com/62913995/84098931-180bb900-a9ce-11ea-9e13-f818874e9180.png)
