### ISSUE TITLE
Seed Data

### ISSUE THREAD

**Issue by luketlancaster** [nss-evening-cohort-12/chatty-zeta-star-wars#4]
## User Story
As a developer, in order to have something on the page, I would like some seed data

## AC
**Given** A developer navigated to your repo
**Then** they should see a file called `helpers/data/messageData.js`
**And** this file should have seed data for 5 messages

### To-do

```
const messageData = [
  {
  id: 01,
  User: 'Stormtrooper 0564',
  Timestamp: 2014-09-08T08:02:17-05:00,
  Body: 'Message Body'
  },
  {
  id: 02,
  User: 'Darth Vader',
  Timestamp: 2014-09-08T08:02:17-05:00,
  Body: 'Message Body'
  },
  ...
];
```
- [x] Create basic modular file structure
- [x] Create messageData file containing an array with our five Star Wars themed "seed" messages
- [x] Object properties will include user (see #8), timestamp (see #9), and the message content itself
