### ISSUE TITLE
Timestamps

### ISSUE THREAD

**Issue by luketlancaster** [nss-evening-cohort-12/chatty-zeta-star-wars#9]
## User Story
As a user, using all the chatting sites, I always see clean looking timestamps.

**Dirty Timestamp:**  2014-09-08T08:02:17-05:00
**Clean Timestamp:**  September 8, 2014 8:02 PM

## AC
**Given** A user navigates to your page
**Then** they see all the messages
**And**  the messages should have nice looking timestamps

## Dev Notes
* Real JS developers hate dates - they use a magical library called [MomentJS](https://momentjs.com/)
```js
npm install moment --save
```
### To-do
- [x] Include property for timestamp
- [x] Fetch current time that message is entered with MomentJs
- [x] Store 'Dirty Timestamp` (2014-09-08T08:02:17-05:00) in data.
- [x] Reformat using MomentJS
- [x] Subtract several thousand years so as to fulfill the "long time ago" part
- [x] Find out what moment does when you push it back into BC times, it might break completely but there's only one way to find out
- [x] Display 'clean'/formatted date above message.
